name: quiz
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  velocity_x: ^4.1.0
  google_fonts: ^4.0.4
  firebase_core: ^2.15.0
  shared_preferences: ^2.2.0
  cloud_firestore: ^4.8.4
  firebase_auth: ^4.7.2
  get: ^4.6.5
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/img1.png
    - assets/images/img2.png
    - assets/images/llave.png
    - assets/images/q1.jpg
    - assets/images/q2.jpg
    - assets/images/q3.jpg
    - assets/images/q4.jpg
    - assets/images/q5.jpg
    - assets/images/q6.png
    - assets/images/q7.png
    - assets/images/q8.png
    - assets/images/q9.jpg
    - assets/images/q10.jpg
    - assets/images/q11.jpg
    - assets/images/q12.jpg
    - assets/images/q14.jpg






  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
